title: Pf6+ User Guide
author: 
copyright: "2021"
logo: images/pf6plus-logo.png
execute:
  execute_notebooks: "off"
repository:    
  url: https://github.com/malariagen/Pf6plus
  path_to_book              : notebooks
  branch                    : master
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
html:
  use_repository_button : true
  use_issues_button: true
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
